version: "3"

services:
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    volumes:
      - ./configure_queen_product_ms.go:/go/src/queen-product-ms/restapi/configure_queen_product_ms.go
    ports:
      - "3000:3000"
